# -*- coding: utf-8 -*-
"""texttoimage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALUsHmRIVHrgBFeyVokGO1Gp74rSPDjo
"""

pip install diffusers

pip install transformers

pip install Pillow

pip install accelerate scipy safetensors

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image

# Replace the model version with your required version if needed
pipeline = StableDiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16
)

print(torch.cuda.is_available())  # Should return True
print(torch.cuda.device_count())  # Number of GPUs available
print(torch.cuda.get_device_name(0))  # Name of the GPU

# Running the inference on GPU with cuda enabled
pipeline = pipeline.to('cuda')

prompt = "tech professional with full of ideas"
image = pipeline(prompt=prompt).images[0]

from IPython.display import display
display(image)